### ISSUE TITLE
Ah yang bener 

### ISSUE THREAD

**Issue by FERDIZ-afk** [naylachan/Anonymous-CHAT#1]
Yang bener tuh DB nya makek sqlite padahal cuman json

**Comment by naylachan** [comment]
> Yang bener tuh DB nya makek sqlite padahal cuman json

Ini saya cuman ambil readme orang, saya recode, lupa hapus yang itu😄

**Comment by FERDIZ-afk** [comment]
Keren ati ati loh kena banned akun wa lu
